import type { CyberTheme, CyberThemeId } from '../types/game';

export const CYBER_THEMES: Record<CyberThemeId, CyberTheme> = {
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Neo Cyberpunk',
    tagline: 'Neon nightscape with cyan laser pylons and magenta grid',
    skyTop: '#070B19',
    skyBottom: '#111827',
    gridColor: '#FF007F',
    gatePrimary: '#00F0FF',
    gateSecondary: '#0284C7',
    gateGlow: 'rgba(0, 240, 255, 0.4)',
    birdVisor: '#00F0FF',
    accent: '#00F0FF',
    accentBg: 'rgba(0, 240, 255, 0.15)',
  },
  synthwave: {
    id: 'synthwave',
    name: 'Synthwave Sunset',
    tagline: '80s retro sunset, violet horizon and electric amber beams',
    skyTop: '#18022B',
    skyBottom: '#4A0E4E',
    gridColor: '#F43F5E',
    gatePrimary: '#F59E0B',
    gateSecondary: '#EA580C',
    gateGlow: 'rgba(245, 158, 11, 0.45)',
    birdVisor: '#FBBF24',
    accent: '#F43F5E',
    accentBg: 'rgba(244, 63, 94, 0.15)',
  },
  matrix: {
    id: 'matrix',
    name: 'Matrix Digital',
    tagline: 'Deep terminal obsidian with emerald code laser gates',
    skyTop: '#020C06',
    skyBottom: '#041F10',
    gridColor: '#10B981',
    gatePrimary: '#10B981',
    gateSecondary: '#059669',
    gateGlow: 'rgba(16, 185, 129, 0.45)',
    birdVisor: '#34D399',
    accent: '#10B981',
    accentBg: 'rgba(16, 185, 129, 0.15)',
  },
  void: {
    id: 'void',
    name: 'Quantum Void',
    tagline: 'Cosmic hyperspace with ion energy plasma columns',
    skyTop: '#0B0A26',
    skyBottom: '#1E1B4B',
    gridColor: '#818CF8',
    gatePrimary: '#818CF8',
    gateSecondary: '#6366F1',
    gateGlow: 'rgba(129, 140, 248, 0.45)',
    birdVisor: '#A5B4FC',
    accent: '#818CF8',
    accentBg: 'rgba(129, 140, 248, 0.15)',
  },
  solar: {
    id: 'solar',
    name: 'Solar Flare Outpost',
    tagline: 'Martian atmospheric plasma and scorched titanium pylons',
    skyTop: '#240600',
    skyBottom: '#451200',
    gridColor: '#FF6B00',
    gatePrimary: '#FF6B00',
    gateSecondary: '#D9480F',
    gateGlow: 'rgba(255, 107, 0, 0.45)',
    birdVisor: '#FFA94D',
    accent: '#FF6B00',
    accentBg: 'rgba(255, 107, 0, 0.18)',
  },
  aurora: {
    id: 'aurora',
    name: 'Arctic Aurora',
    tagline: 'Glacial cryo-polar skies with luminous boreal wave barriers',
    skyTop: '#021B29',
    skyBottom: '#0A3A40',
    gridColor: '#20C997',
    gatePrimary: '#38D9A9',
    gateSecondary: '#12B886',
    gateGlow: 'rgba(56, 217, 169, 0.45)',
    birdVisor: '#63E6BE',
    accent: '#20C997',
    accentBg: 'rgba(32, 201, 151, 0.15)',
  },
  citadel: {
    id: 'citadel',
    name: 'Apex Citadel',
    tagline: 'Sleek gilded obsidian spire with royal quantum conduits',
    skyTop: '#141108',
    skyBottom: '#2B210B',
    gridColor: '#F59E0B',
    gatePrimary: '#FBBF24',
    gateSecondary: '#D97706',
    gateGlow: 'rgba(251, 191, 36, 0.45)',
    birdVisor: '#FDE68A',
    accent: '#F59E0B',
    accentBg: 'rgba(245, 158, 11, 0.18)',
  },
  acid: {
    id: 'acid',
    name: 'Acid Overdrive',
    tagline: 'Hyper-saturated ultraviolet laser grid and radioactive neon',
    skyTop: '#180424',
    skyBottom: '#270838',
    gridColor: '#CCFF00',
    gatePrimary: '#CCFF00',
    gateSecondary: '#99E600',
    gateGlow: 'rgba(204, 255, 0, 0.45)',
    birdVisor: '#E6FF66',
    accent: '#CCFF00',
    accentBg: 'rgba(204, 255, 0, 0.18)',
  },
};

import type { BirdCraft, BirdCraftId } from '../types/game';

export const BIRD_CRAFTS: Record<BirdCraftId, BirdCraft> = {
  falcon: {
    id: 'falcon',
    name: 'Cyber Falcon X-1',
    designation: 'FX-01 INTERCEPTOR',
    classType: 'Aerodynamic Recon',
    description: 'High-agility carbon-titanium airframe with twin cyan ion thrusters and forward canard wings.',
    hullColor: '#1E293B',
    accentColor: '#00F0FF',
    visorColor: '#00F0FF',
    thrusterColor: '#00F0FF',
    wingSpanFactor: 1.0,
  },
  phoenix: {
    id: 'phoenix',
    name: 'Plasma Phoenix F-99',
    designation: 'PX-99 VANGUARD',
    classType: 'Thermal Overdrive',
    description: 'Forged from stellar shielding alloys with fiery hyper-plasma exhaust and swept delta wings.',
    hullColor: '#2D1515',
    accentColor: '#FF3366',
    visorColor: '#FF9900',
    thrusterColor: '#FF4500',
    wingSpanFactor: 1.25,
  },
  raven: {
    id: 'raven',
    name: 'Void Raven Spec-Ops',
    designation: 'VR-07 GHOST',
    classType: 'Stealth Infiltrator',
    description: 'Radar-absorbent matte obsidian fuselage emitting quiet ultraviolet quantum wake vortices.',
    hullColor: '#0F0E17',
    accentColor: '#A855F7',
    visorColor: '#C084FC',
    thrusterColor: '#8B5CF6',
    wingSpanFactor: 1.1,
  },
  hummingbird: {
    id: 'hummingbird',
    name: 'Neon Hummingbird',
    designation: 'HB-03 KINETIC',
    classType: 'Ultra-Compact Micro',
    description: 'Micro-scale hyper-frequency oscillating kinetic wings designed for pinpoint obstacle navigation.',
    hullColor: '#062018',
    accentColor: '#10B981',
    visorColor: '#34D399',
    thrusterColor: '#10B981',
    wingSpanFactor: 0.85,
  },
  osprey: {
    id: 'osprey',
    name: 'Mech Osprey Heavy',
    designation: 'OS-88 TANK',
    classType: 'Heavy Armored Assault',
    description: 'Industrial reinforced tungsten fuselage with dual heavy tilt-turbines and reinforced sensor dome.',
    hullColor: '#292524',
    accentColor: '#F59E0B',
    visorColor: '#FBBF24',
    thrusterColor: '#F59E0B',
    wingSpanFactor: 1.3,
  },
  specter: {
    id: 'specter',
    name: 'Quantum Specter Phase',
    designation: 'QS-00 PROTOTYPE',
    classType: 'Phase Distortion Craft',
    description: 'Experimental craft engineered with phase-shifting nanites and chromatic prismatic energy trails.',
    hullColor: '#091E2A',
    accentColor: '#00FFA3',
    visorColor: '#00FFA3',
    thrusterColor: '#00E5FF',
    wingSpanFactor: 1.15,
  },
  goddess: {
    id: 'goddess',
    name: 'Aethelia // Goddess of Games',
    designation: 'DEITY-01 APEX DIVINE',
    classType: 'Celestial Sovereign',
    description: 'Reborn from the fragments of the fallen 2014 retro bird. Radiates golden astral halos, prismatic feather wings, and celestial overdrive aura.',
    hullColor: '#181124',
    accentColor: '#FFD700',
    visorColor: '#00F0FF',
    thrusterColor: '#FFD700',
    wingSpanFactor: 1.5,
  },
};

export function getBirdCraft(id?: BirdCraftId): BirdCraft {
  if (id && BIRD_CRAFTS[id]) return BIRD_CRAFTS[id];
  return BIRD_CRAFTS.falcon;
}

export interface SectorColorStage {
  scoreThreshold: number;
  sectorName: string;
  headline: string;
  subtitle: string;
  gatePrimary: string;
  gateSecondary: string;
  gateGlow: string;
  gridColor: string;
  skyTop: string;
  skyBottom: string;
  birdVisor: string;
  accent: string;
}

export const SECTOR_STAGES: SectorColorStage[] = [
  {
    scoreThreshold: 0,
    sectorName: 'NEON CYAN',
    headline: 'READY FOR TAKEOFF!',
    subtitle: 'Sector 1 // Warp Thrusters Engaged',
    gatePrimary: '#00F0FF',
    gateSecondary: '#0284C7',
    gateGlow: 'rgba(0, 240, 255, 0.45)',
    gridColor: '#00F0FF',
    skyTop: '#070B19',
    skyBottom: '#0F172A',
    birdVisor: '#00F0FF',
    accent: '#00F0FF',
  },
  {
    scoreThreshold: 10,
    sectorName: 'SYNTH MAGENTA',
    headline: '✨ WOW! WELL DONE! ✨',
    subtitle: 'Color Shift: Synth Magenta // 10 PTS Cleared!',
    gatePrimary: '#FF007F',
    gateSecondary: '#BE185D',
    gateGlow: 'rgba(255, 0, 127, 0.5)',
    gridColor: '#FF007F',
    skyTop: '#180224',
    skyBottom: '#3B0764',
    birdVisor: '#FF2A85',
    accent: '#FF007F',
  },
  {
    scoreThreshold: 20,
    sectorName: 'MATRIX EMERALD',
    headline: '⚡ WELL DONE! INCREDIBLE! ⚡',
    subtitle: 'Color Shift: Matrix Emerald // 20 PTS Cleared!',
    gatePrimary: '#10B981',
    gateSecondary: '#059669',
    gateGlow: 'rgba(16, 185, 129, 0.5)',
    gridColor: '#10B981',
    skyTop: '#021408',
    skyBottom: '#052E16',
    birdVisor: '#34D399',
    accent: '#10B981',
  },
  {
    scoreThreshold: 30,
    sectorName: 'SOLAR FLARE AMBER',
    headline: '🔥 WOW! UNSTOPPABLE! 🔥',
    subtitle: 'Color Shift: Solar Flare // 30 PTS Cleared!',
    gatePrimary: '#F59E0B',
    gateSecondary: '#D97706',
    gateGlow: 'rgba(245, 158, 11, 0.5)',
    gridColor: '#F59E0B',
    skyTop: '#1F0A00',
    skyBottom: '#451A03',
    birdVisor: '#FBBF24',
    accent: '#F59E0B',
  },
  {
    scoreThreshold: 40,
    sectorName: 'QUANTUM VIOLET',
    headline: '🚀 WELL DONE! HYPER SPEED! 🚀',
    subtitle: 'Color Shift: Quantum Violet // 40 PTS Cleared!',
    gatePrimary: '#A855F7',
    gateSecondary: '#7E22CE',
    gateGlow: 'rgba(168, 85, 247, 0.5)',
    gridColor: '#C084FC',
    skyTop: '#0B0826',
    skyBottom: '#2E1065',
    birdVisor: '#C084FC',
    accent: '#A855F7',
  },
  {
    scoreThreshold: 50,
    sectorName: 'HYPER CRIMSON',
    headline: '👑 WOW! GODLIKE PILOT! 👑',
    subtitle: 'Color Shift: Hyper Crimson // 50 PTS Cleared!',
    gatePrimary: '#FF3366',
    gateSecondary: '#BE123C',
    gateGlow: 'rgba(255, 51, 102, 0.55)',
    gridColor: '#FF3366',
    skyTop: '#1F050D',
    skyBottom: '#4C0519',
    birdVisor: '#FF5E85',
    accent: '#FF3366',
  },
  {
    scoreThreshold: 60,
    sectorName: 'PRISMATIC OVERDRIVE',
    headline: '💎 LEGENDARY! WELL DONE! 💎',
    subtitle: 'Color Shift: Prismatic Overdrive // 60+ PTS Master!',
    gatePrimary: '#00FFA3',
    gateSecondary: '#00B8D9',
    gateGlow: 'rgba(0, 255, 163, 0.5)',
    gridColor: '#00FFA3',
    skyTop: '#051923',
    skyBottom: '#003554',
    birdVisor: '#00FFA3',
    accent: '#00FFA3',
  },
];

export function getSectorStage(score: number): SectorColorStage {
  const stageIndex = Math.floor(score / 10);
  if (stageIndex === 0) return SECTOR_STAGES[0];
  const cycleCount = SECTOR_STAGES.length - 1; // 6 progressive stages
  const resolvedIdx = 1 + ((stageIndex - 1) % cycleCount);
  return SECTOR_STAGES[resolvedIdx];
}
